"""Downward-symlink composition for personality-specific entries.

Part-D commit 5 (corrected) contract:

* **Globals** — capability templates write the agent surface
  (commands, skills, plugins) directly into ``.opencode/`` once per
  project. These remain real files at
  ``.opencode/<kind>/<basename>``.

* **Per-personality slots** — every personality dir holds its own
  empty ``commands/`` and ``skills/`` real directories. The agent
  may write personality-specific commands/skills into these at
  runtime.

* **Discovery** — for each entry inside ``personalities/<p>/<kind>/``,
  ``compose()`` creates a **downward symlink**
  ``.opencode/<kind>/<basename> → personalities/<p>/<kind>/<basename>``
  so OpenCode picks the file up from its global ``.opencode/`` scan.
  Without that symlink, OpenCode never sees personality-specific
  entries.

Conflict semantics: if ``.opencode/<kind>/<basename>`` already
exists (a global capability file or another personality's symlink
of the same name), compose surfaces a ``ComposeConflict``; the
personality's entry stays untouched, and ``/sync`` resolves it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from click.testing import CliRunner

from allmight.cli import main


@pytest.fixture
def initted_project(tmp_path: Path) -> Path:
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("def hello(): pass\n")
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'demo'\n")

    runner = CliRunner()
    result = runner.invoke(main, ["init", "--yes", str(tmp_path)])
    assert result.exit_code == 0, result.output
    return tmp_path


def _personalities(root: Path) -> list[Path]:
    base = root / "personalities"
    if not base.exists():
        return []
    return sorted(p for p in base.iterdir() if p.is_dir() and not p.is_symlink())


class TestPersonalityDirsAreRealEmpty:
    def test_each_personality_has_real_commands_dir(self, initted_project: Path) -> None:
        personalities = _personalities(initted_project)
        assert personalities, "init must produce at least one personality"
        for p in personalities:
            cmd_dir = p / "commands"
            assert cmd_dir.is_dir(), (
                f"{cmd_dir.relative_to(initted_project)} must be a real dir"
            )
            assert not cmd_dir.is_symlink(), (
                f"{cmd_dir.relative_to(initted_project)} must NOT be a symlink "
                "— it's the personality's own slot for custom commands."
            )

    def test_each_personality_has_real_skills_dir(self, initted_project: Path) -> None:
        for p in _personalities(initted_project):
            sk_dir = p / "skills"
            assert sk_dir.is_dir()
            assert not sk_dir.is_symlink()

    def test_personality_dirs_start_empty(self, initted_project: Path) -> None:
        """At init time, personalities have no custom commands/skills.

        Only globals (in ``.opencode/``) are populated by capability
        templates.
        """
        for p in _personalities(initted_project):
            for kind in ("commands", "skills"):
                d = p / kind
                contents = list(d.iterdir())
                assert not contents, (
                    f"{d.relative_to(initted_project)} must start empty; "
                    f"got {[c.name for c in contents]}"
                )


class TestGlobalsLiveAtOpencode:
    def test_global_commands_are_real_files(self, initted_project: Path) -> None:
        opencode_commands = initted_project / ".opencode" / "commands"
        assert opencode_commands.is_dir()
        files = [f for f in opencode_commands.iterdir() if f.is_file()]
        assert files, "No global commands generated by capability templates"
        for f in files:
            assert not f.is_symlink(), (
                f"{f.relative_to(initted_project)} is a symlink — "
                f"capability-written globals should be real files."
            )


class TestComposeSymlinksPersonalityEntriesIntoOpencode:
    def test_personality_command_becomes_opencode_symlink(
        self, initted_project: Path,
    ) -> None:
        """Drop a custom command into a personality dir, run compose,
        and verify it appears in ``.opencode/commands/`` as a symlink."""
        from allmight.core.personalities import (
            Personality,
            PersonalityTemplate,
            compose,
        )

        personalities = _personalities(initted_project)
        target = personalities[0]
        custom = target / "commands" / "stdcell-special.md"
        custom.write_text("# stdcell-special command body\n")

        tpl = PersonalityTemplate(
            name="t", short_name="t", version="1.0.0", description="",
            owned_paths=[], cli_options=[],
            install=lambda ctx, instance: None,  # type: ignore[arg-type]
            status=lambda root, instance: None,  # type: ignore[arg-type]
        )
        instance = Personality(
            template=tpl, project_root=initted_project,
            name=target.name, options={},
        )

        conflicts = compose(initted_project, instance)
        assert conflicts == [], conflicts

        link = initted_project / ".opencode" / "commands" / "stdcell-special.md"
        assert link.is_symlink(), (
            "Custom personality command must be discoverable from "
            ".opencode/commands/ via a symlink."
        )
        assert link.resolve() == custom.resolve()

    def test_collision_with_global_is_a_conflict(
        self, initted_project: Path,
    ) -> None:
        """If a personality writes a command whose name clashes with a
        capability-written global, compose refuses and reports."""
        from allmight.core.personalities import (
            Personality,
            PersonalityTemplate,
            compose,
        )

        target = _personalities(initted_project)[0]
        clashing = target / "commands" / "search.md"
        clashing.write_text("# personality's own search.md\n")

        tpl = PersonalityTemplate(
            name="t", short_name="t", version="1.0.0", description="",
            owned_paths=[], cli_options=[],
            install=lambda ctx, instance: None,  # type: ignore[arg-type]
            status=lambda root, instance: None,  # type: ignore[arg-type]
        )
        instance = Personality(
            template=tpl, project_root=initted_project,
            name=target.name, options={},
        )

        conflicts = compose(initted_project, instance)
        assert len(conflicts) == 1
        c = conflicts[0]
        assert c.kind == "commands"
        assert c.basename == "search.md"
        # Personality's file untouched; global still wins on disk.
        assert clashing.read_text() == "# personality's own search.md\n"
        global_path = initted_project / ".opencode" / "commands" / "search.md"
        assert not global_path.is_symlink()
